#ifndef _LINUX_IF_SWITCH_H
#define _LINUX_IF_SWITCH_H

#include <linux/types.h>

#define SIOCGTYPE	(SIOCDEVPRIVATE + 0)
#define SIOCGSWITCH	(SIOCDEVPRIVATE + 1)
#define SIOCSTXBW	(SIOCDEVPRIVATE + 2)
#define SIOCSRXBW	(SIOCDEVPRIVATE + 3)
#define SIOCSMASTER	(SIOCDEVPRIVATE + 4)
#define SIOCSMIRROR	(SIOCDEVPRIVATE + 5)
#define SIOCGREG	(SIOCDEVPRIVATE + 8)
#define SIOCSREG	(SIOCDEVPRIVATE + 9)
#define SIOCGPORT	(SIOCDEVPRIVATE + 10)

#define SWITCH_ADMTEK		0
#define SWITCH_ICPLUS175C	1

#define MIRROR_NONE -1u
#define MIRROR_CPU -2u


#endif
